version: "2.2"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.02.6.1}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-23-02-6-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - 6819
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.02.6.1}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    environment:
      LD_LIBRARY_PATH: /usr/local/lib:/usr/lib64
#      SLURM_JWT: daemon
      SLURMRESTD_HOST: 0.0.0.0
      SLURMRESTD_PORT: 6820
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - work:/home/admin
    expose:
      - 6817
    ports:
      - 6820:6820
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.02.6.1}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - work:/home/admin
    expose:
      - 6818
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.02.6.1}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - work:/home/admin
    privileged: true
    expose:
      - 6818
    depends_on:
      - "slurmctld"

  slurmjupyter:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.02.6.1}
    command: ["jupyter"]
    hostname: slurmjupyter
    container_name: slurmjupyter
#    user: admin
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - work:/home/admin
    ports:
      - 8888:8888
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  work:
